### ISSUE TITLE
Target overrides the ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES

### ISSUE THREAD

**Issue by codymoorhouse** [Alamofire/Alamofire#1573]
When I run pod update:
> 
> [!] The `*** [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-bootmark/Pods-bootmark.debug.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `*** [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-bootmark/Pods-bootmark.release.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.

I am using cocoapods 1.1.0.rc.2 with a deployment target of 10.0. I am also using alamofire 4.0. Any suggestions?

These people are also experiencing the same issue so far:
@GZaccaroni 
@jonybur 
@SMR 
@realmike33
@msilva

I thought I would make this it's own issue since no one seemed to be getting back to the closed issue (which totally makes sense). SEE ISSUE: #1531

**Comment by codymoorhouse** [comment]
@GZaccaroni @jonybur @SMR @realmike33 @msilva @PlayApple

Alright guys not the cleanest solution to the problem, but here is how I fixed it. Turns out this isn't really an Alamofire issue and shouldn't be on here specifically. Basically I went into the build settings and just cleared all the settings to default. So anything that was bold coloured, I selected and then I pushed delete. This is what worked for me.

![screen shot 2016-09-19 at 7 53 54 pm](https://cloud.githubusercontent.com/assets/10747839/18655201/080afd8a-7ea4-11e6-922d-eb290bed7d04.png)

**Comment by grantkemp** [comment]
Thanks for posting this - It really needs to go in the Cocoapods Readme.

**Comment by speedoholic** [comment]
Pleae check issue <a href="https://github.com/CocoaPods/CocoaPods/issues/5981">#5981</a> and follow the steps posted by johnantoni on 9 Jan 2017. It worked for my project with cocoapod dependencies. Xcode Version 8.1

**Comment by jshier** [comment]
This is fixed in CocoaPods 1.2.0, so there should be no need for that workaround anymore.

**Comment by jeffreyjackson** [comment]
@jshier I'm still seeing this bug.  Im currently on cocoapods 1.2.1, any ideas?
