### ISSUE TITLE
Swift Concurrency: "Type 'Any' does not conform to the 'Sendable' protocol" in Alamofire ResponseSerializer

### ISSUE THREAD

**Issue by suhaankataria** [Alamofire/Alamofire#3957]
Problem
I cloned [Alamofire](https://github.com/Alamofire/Alamofire) (version 5.10.2) directly from its GitHub repo and tried to build it using Xcode 16.3 (Swift 6.1). However, I'm getting multiple compiler errors related to Swift Concurrency and the Sendable protocol.

Steps I Took
Cloned Alamofire using:
git clone https://github.com/Alamofire/Alamofire.git
Opened the project in Xcode 16.3
Tried to build it using Product > Build

Errors I'm Seeing

Source/Features/ResponseSerialization.swift:360:20: Type 'Any' does not conform to the 'Sendable' protocol

Environment
Xcode: 16.3

Swift: 6.1

Alamofire: 5.10.2 (directly cloned)

Platform:  macOS (15.4)

Is this a known issue when using Alamofire directly with Swift Concurrency enabled?
How can I safely resolve the Sendable protocol errors when building Alamofire from source?

Should I avoid building Alamofire manually and use Swift Package Manager/CocoaPods instead?

Is there an officially supported version that compiles cleanly with Swift Concurrency?

Any guidance would be appreciated!

**Comment by jshier** [comment]
Unfortunately it's not possible to fix this warning in a source compatible way, so it will always be there for Alamofire 5. However, they shouldn't be errors, as Alamofire builds in Swift 5 mode by default, which is compatible with projects in 5 *and* 6 mode. If you're integrating Alamofire into a project, yes, you should use a dependency manager (likely SPM).

These issues can only be resolved in a new major version, so Alamofire 6 development may start soon.

**Comment by suhaankataria** [comment]
However, in my case, the issue isn’t just isolated to building Alamofire manually—the Sendable-related errors are breaking the build in my actual Swift 6.1 project.
I’m not modifying the Alamofire source, but because my project is compiled under Swift 6’s stricter concurrency checks, these issues surface and cause hard errors, not just warnings.

Could you clarify if there's a recommended workaround for this situation?
do I need to suppress these errors using a compiler flag?

If there’s no workaround, would you consider tagging a transitional release with limited Swift 6 compatibility while Alamofire 6 is in development?

**Comment by jshier** [comment]
How are you integrating Alamofire into your project? In any way aside from direct source inclusion, the Alamofire module should still build fine under Swift 5 mode. Are you overriding that setting at the workspace or project level? Do you have warnings as errors turned on?

In any case, all you really need to do is integrate Alamofire using a proper dependency manager like SPM, then your local project settings won't affect packages at all.

**Comment by suhaankataria** [comment]
We cloned the Alamofire repo and tried to build it directly in Swift 6, but the build failed due to Sendable-related errors.

To work around this, we changed the Swift version to 5 for the Alamofire target so it would compile.

After that, we manually integrated the compiled build files of Alamofire into our main project.

However, even when we tried integrating Alamofire using SPM, it still failed to compile — because our project is set to use Swift 6 globally (i.e., we’ve overridden the default Swift language version across all targets and dependencies).

So yes, the errors are showing up even when using SPM, due to our global Swift 6 setting.

Is there a supported way to force SPM packages like Alamofire to compile in Swift 5 mode, independent of the project's global setting? Or should we be managing Swift language versions on a per-target basis to avoid this issue?

Appreciate your guidance on the best path forward.

**Comment by jshier** [comment]
The best path forward is to stop overriding the Swift mode for your dependencies. Not only is it completely unnecessary, but many, like Alamofire, aren't designed to build in that mode in the first place. There's no advantage to forcing them, as the Swift 6 compiler is designed to work seamlessly with mixed 5 and 6 mode modules. If you insist on doing so, feel free to fork Alamofire and remove the offending bits.
