### ISSUE TITLE
Xcode7 beta : Error : Compiled With older version of compiler

### ISSUE THREAD

**Issue by hitendradeveloper** [Alamofire/Alamofire#517]
I have opened the current project using Xcode 7 beta,

when I am trying to compile, getting error : Module Alamofire converted using older compiler

I have tried to convert the code using converter provide with xcode 7 beta
it is showing error : 
1 ) import Alamofire :=> Error :  could not build objective-c modul Alamofire

2) module Alamofire.Swift {
    header "Alamofire-Swift.h" :=> Error : Header Alamofire-swift.h not found
}

**Comment by NicholasTD07** [comment]
I think we need a swift-2 branch like some other Swift frameworks, e.g. Quick/Quick, Quick/Nimble, thoughtbot/Argo.

I also tried to convert it to Swift 2. But for some reason, Xcode 7 would only convert code in Alamofire itself but not the ones in test. Not sure why.

Did it convert all the code for you, including code in Alamofire, test, and examlp app? @hitendradeveloper

**Comment by hitendradeveloper** [comment]
I am compiling my own project, but yes converter also converted my own code.
I have just remove test module, so don't have idea about test module conversion.

**Comment by rpowelll** [comment]
From what I can tell, it doesn't convert testing targets. That said, the surface level syntax changes are pretty easy to implement.

**Comment by NicholasTD07** [comment]
@hitendradeveloper Yeah, I was compiling my own project too, but Alamofire is the one dependency that dont yet have a Swift 2 branch.

@rpowelll I am working on a Swift 2 version of Alamofire.

It is easy, it's just so many little changes and Xcode couldn't do all of it for you. Plus, it sometimes gets some text inserted in the wrong place...

**Comment by NicholasTD07** [comment]
@hitendradeveloper Could you change the title of this Issue to something like "Support for Swift 2"? I think this is more related to Swift 2. Also see below. :)

@rpowelll 

I've created a pull request for support for Swift 2. See the pull request here #518 
I fixed most of the things, however, there are two places I didn't know how to get it right. If you guys can help me on those two todo/fixme, it would be great. Thanks!

**Comment by rromanchuk** [comment]
Shouldn't this still work with xcode7 as is though? Users still have the choice of not upgrading to swift2 while using xcode7, aren't we just missing a compiler flag here?  I mean, we will need a Swift 2 branch regardless, but I would assume this would work out of the box.

**Comment by abunur** [comment]
It does not work out of the box.  In fact, after installing Xcode 7 beta, even running the release version of Xcode I am now getting the compiler errors related to Swift 2 regardless of whether I choose to convert the project to Swift 2 or not.  The option to convert to Swift 2 is just a way to resolve the errors.  As I recall they made it so that you no longer need to update your Xcode to update your Swift version, although I’m not exactly sure how this works.  On another machine as long as I don’t install the Xcode 7 beta I don’t see the Swift 2 errors.

**Comment by rpowelll** [comment]
Yep, Swift 2 is non-optional for Xcode 7.

**Comment by cnoon** [comment]
Hey everyone, thanks for all the feedback here! Apologies for not getting a chance to comment on all this until now. Busy week at WWDC.

I'm going to start working on Swift 2.0 support tonight. I'll be pushing up a new `swift-2.0` branch that everyone will need to use until Xcode 7 reaches GM. Once the GM is released, we'll pull the `swift-2.0` branch into `master` and cut another release, just like we've been doing in the past with Swift 1.1 and 1.2.

Cheers 🍻

**Comment by dslysenko** [comment]
@cnoon, the swift-2.0 branch is 82 commits behind master. What is the status of swift 2.0 support, out of curiosity?

**Comment by cnoon** [comment]
Hi @dslysenko, believe me, we're aware. We've been hard at work pushing the 1.3.0 release out the door. All efforts are now being focused on porting each and every one of those commits over to the `swift-2.0` branch.

* https://twitter.com/AlamofireSF/status/624734484609368064

Stay tuned.
